apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraform
  template:
    metadata:
      labels:
        app: terraform
    spec:
      serviceAccountName: {{ include "terraform-server-helm-chart.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: terraform
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /terraform
          command: ["/bin/sh"]
          args: ["-c", "tail -f /dev/null"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: terraform-storage
              mountPath: /terraform
      volumes:
        - name: terraform-storage
          persistentVolumeClaim:
            claimName: terraform-pvc