apiVersion: v1
kind: Service
metadata:
  name: terraform
spec:
  selector:
    app: terraform
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}